# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Nomad
      include NomadAclAuthMethod
      include NomadAclBindingRule
      include NomadAclPolicy
      include NomadAclRole
      include NomadAclToken
      include NomadCsiVolume
      include NomadCsiVolumeRegistration
      include NomadDynamicHostVolume
      include NomadDynamicHostVolumeRegistration
      include NomadExternalVolume
      include NomadJob
      include NomadNamespace
      include NomadNodePool
      include NomadQuotaSpecification
      include NomadSchedulerConfig
      include NomadSentinelPolicy
      include NomadVariable
      include NomadVolume
    end
  end
end
