# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_acl_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadAclPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_acl_policy,
      attributes_class: Nomad::Types::AclPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :rules_hcl],
      map_present: [:description, :job_acl]
  end
  module Nomad
    include NomadAclPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
