# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class AclPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :name, T::String
    attribute :rules_hcl, T::String
    attribute? :description, T::String.optional
    attribute? :job_acl, T::Array.of(T::Hash).optional
  end
end
