# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_node_pool/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadNodePool
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_node_pool,
      attributes_class: Nomad::Types::NodePoolAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :meta, :scheduler_config]
  end
  module Nomad
    include NomadNodePool
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
