# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_acl_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadAclRole
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_acl_role,
      attributes_class: Nomad::Types::AclRoleAttributes,
      outputs: { id: :id },
      map: [:name, :policy],
      map_present: [:description]
  end
  module Nomad
    include NomadAclRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
