# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_namespace/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadNamespace
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_namespace,
      attributes_class: Nomad::Types::NamespaceAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:capabilities, :description, :meta, :node_pool_config, :quota]
  end
  module Nomad
    include NomadNamespace
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
