# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class NamespaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :name, T::String
    attribute? :capabilities, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :meta, T::Hash.optional
    attribute? :node_pool_config, T::Array.of(T::Hash).optional
    attribute? :quota, T::String.optional
  end
end
