# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_sentinel_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadSentinelPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_sentinel_policy,
      attributes_class: Nomad::Types::SentinelPolicyAttributes,
      outputs: { id: :id },
      map: [:enforcement_level, :name, :policy, :scope],
      map_present: [:description]
  end
  module Nomad
    include NomadSentinelPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
