# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_dynamic_host_volume_registration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadDynamicHostVolumeRegistration
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_dynamic_host_volume_registration,
      attributes_class: Nomad::Types::DynamicHostVolumeRegistrationAttributes,
      outputs: { id: :id },
      map: [:capability, :host_path, :name, :node_id],
      map_present: [:capacity, :namespace, :parameters]
  end
  module Nomad
    include NomadDynamicHostVolumeRegistration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
