# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class DynamicHostVolumeRegistrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :capability, T::Array.of(T::Hash)
    attribute :host_path, T::String
    attribute :name, T::String
    attribute :node_id, T::String
    attribute? :capacity, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :parameters, T::Hash.optional
  end
end
