# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_acl_binding_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadAclBindingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_acl_binding_rule,
      attributes_class: Nomad::Types::AclBindingRuleAttributes,
      outputs: { id: :id },
      map: [:auth_method, :bind_type],
      map_present: [:bind_name, :description, :selector]
  end
  module Nomad
    include NomadAclBindingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
