# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class AclBindingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :auth_method, T::String
    attribute :bind_type, T::String
    attribute? :bind_name, T::String.optional
    attribute? :description, T::String.optional
    attribute? :selector, T::String.optional
  end
end
