# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_acl_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadAclToken
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_acl_token,
      attributes_class: Nomad::Types::AclTokenAttributes,
      outputs: { id: :id },
      map: [:type],
      map_present: [:expiration_ttl, :name, :policies, :role],
      map_bool: [:global]
  end
  module Nomad
    include NomadAclToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
