# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class AclTokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :type, T::String
    attribute? :expiration_ttl, T::String.optional
    attribute? :global, T::Bool.optional
    attribute? :name, T::String.optional
    attribute? :policies, T::Array.of(T::String).optional
    attribute? :role, T::Array.of(T::Hash).optional
  end
end
