# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Nomad resources
require_relative 'pangea/resources/nomad_acl_auth_method/resource'
require_relative 'pangea/resources/nomad_acl_binding_rule/resource'
require_relative 'pangea/resources/nomad_acl_policy/resource'
require_relative 'pangea/resources/nomad_acl_role/resource'
require_relative 'pangea/resources/nomad_acl_token/resource'
require_relative 'pangea/resources/nomad_csi_volume/resource'
require_relative 'pangea/resources/nomad_csi_volume_registration/resource'
require_relative 'pangea/resources/nomad_dynamic_host_volume/resource'
require_relative 'pangea/resources/nomad_dynamic_host_volume_registration/resource'
require_relative 'pangea/resources/nomad_external_volume/resource'
require_relative 'pangea/resources/nomad_job/resource'
require_relative 'pangea/resources/nomad_namespace/resource'
require_relative 'pangea/resources/nomad_node_pool/resource'
require_relative 'pangea/resources/nomad_quota_specification/resource'
require_relative 'pangea/resources/nomad_scheduler_config/resource'
require_relative 'pangea/resources/nomad_sentinel_policy/resource'
require_relative 'pangea/resources/nomad_variable/resource'
require_relative 'pangea/resources/nomad_volume/resource'

# Nomad module aggregator
require_relative 'pangea/resources/nomad'
