# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_variable/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadVariable
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_variable,
      attributes_class: Nomad::Types::VariableAttributes,
      outputs: { id: :id },
      map: [:items, :path],
      map_present: [:namespace]
  end
  module Nomad
    include NomadVariable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
