# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_quota_specification/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadQuotaSpecification
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_quota_specification,
      attributes_class: Nomad::Types::QuotaSpecificationAttributes,
      outputs: { id: :id },
      map: [:limits, :name],
      map_present: [:description]
  end
  module Nomad
    include NomadQuotaSpecification
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
