# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class QuotaSpecificationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :limits, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute? :description, T::String.optional
  end
end
