# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_scheduler_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadSchedulerConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_scheduler_config,
      attributes_class: Nomad::Types::SchedulerConfigAttributes,
      outputs: { id: :id },
      map_present: [:preemption_config, :scheduler_algorithm],
      map_bool: [:memory_oversubscription_enabled]
  end
  module Nomad
    include NomadSchedulerConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
