# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class SchedulerConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute? :memory_oversubscription_enabled, T::Bool.optional
    attribute? :preemption_config, T::Hash.optional
    attribute? :scheduler_algorithm, T::String.optional
  end
end
