# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_acl_auth_method/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadAclAuthMethod
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_acl_auth_method,
      attributes_class: Nomad::Types::AclAuthMethodAttributes,
      outputs: { id: :id },
      map: [:config, :max_token_ttl, :name, :token_locality, :type],
      map_present: [:token_name_format],
      map_bool: [:default]
  end
  module Nomad
    include NomadAclAuthMethod
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
