# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class AclAuthMethodAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :config, T::Array.of(T::Hash)
    attribute :max_token_ttl, T::String
    attribute :name, T::String
    attribute :token_locality, T::String
    attribute :type, T::String
    attribute? :default, T::Bool.optional
    attribute? :token_name_format, T::String.optional
  end
end
