# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_dynamic_host_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadDynamicHostVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_dynamic_host_volume,
      attributes_class: Nomad::Types::DynamicHostVolumeAttributes,
      outputs: { id: :id },
      map: [:capability, :name, :plugin_id],
      map_present: [:capacity_max, :capacity_min, :constraint, :namespace, :parameters]
  end
  module Nomad
    include NomadDynamicHostVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
