# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class DynamicHostVolumeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :capability, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :plugin_id, T::String
    attribute? :capacity_max, T::String.optional
    attribute? :capacity_min, T::String.optional
    attribute? :constraint, T::Array.of(T::Hash).optional
    attribute? :namespace, T::String.optional
    attribute? :parameters, T::Hash.optional
  end
end
