# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_volume,
      attributes_class: Nomad::Types::VolumeAttributes,
      outputs: { id: :id },
      map: [:external_id, :name, :plugin_id, :volume_id],
      map_present: [:access_mode, :attachment_mode, :capability, :context, :mount_options, :namespace, :parameters, :secrets, :topology_request, :type],
      map_bool: [:deregister_on_destroy]
  end
  module Nomad
    include NomadVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
