# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class VolumeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :external_id, T::String
    attribute :name, T::String
    attribute :plugin_id, T::String
    attribute :volume_id, T::String
    attribute? :access_mode, T::String.optional
    attribute? :attachment_mode, T::String.optional
    attribute? :capability, T::Array.of(T::Hash).optional
    attribute? :context, T::Hash.optional
    attribute? :deregister_on_destroy, T::Bool.optional
    attribute? :mount_options, T::Array.of(T::Hash).optional
    attribute? :namespace, T::String.optional
    attribute? :parameters, T::Hash.optional
    attribute? :secrets, T::Hash.optional
    attribute? :topology_request, T::Array.of(T::Hash).optional
    attribute? :type, T::String.optional
  end
end
