# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_csi_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadCsiVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_csi_volume,
      attributes_class: Nomad::Types::CsiVolumeAttributes,
      outputs: { id: :id },
      map: [:capability, :name, :plugin_id, :volume_id],
      map_present: [:capacity_max, :capacity_min, :clone_id, :mount_options, :namespace, :parameters, :secrets, :snapshot_id, :topology_request]
  end
  module Nomad
    include NomadCsiVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
