# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_csi_volume_registration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadCsiVolumeRegistration
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_csi_volume_registration,
      attributes_class: Nomad::Types::CsiVolumeRegistrationAttributes,
      outputs: { id: :id },
      map: [:external_id, :name, :plugin_id, :volume_id],
      map_present: [:capability, :capacity_max, :capacity_min, :context, :mount_options, :namespace, :parameters, :secrets, :topology_request],
      map_bool: [:deregister_on_destroy]
  end
  module Nomad
    include NomadCsiVolumeRegistration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
