# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_sentinel_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadSentinelPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enforcement_level: 'test-value', name: 'test-value', policy: 'test-value', scope: 'test-value' } }

  describe ':nomad_sentinel_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_sentinel_policy', 'test')
        validate_required_attributes(config, [:enforcement_level, :name, :policy, :scope])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_sentinel_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_sentinel_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_sentinel_policy('test', required_attrs)

        expect(ref.id).to eq("${nomad_sentinel_policy.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_sentinel_policy', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_sentinel_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_sentinel_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_sentinel_policy', 'typed')
        expect(config['enforcement_level']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['policy']).to be_a(String)
        expect(config['scope']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_sentinel_policy('first', required_attrs)
        synth.nomad_sentinel_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_sentinel_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_sentinel_policy,
    method: :nomad_sentinel_policy,
    required_attrs: { enforcement_level: 'test-value', name: 'test-value', policy: 'test-value', scope: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
