# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_dynamic_host_volume_registration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadDynamicHostVolumeRegistration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { capability: [{ 'key1' => 'val1' }], host_path: 'test-value', name: 'test-value', node_id: 'test-value' } }

  describe ':nomad_dynamic_host_volume_registration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'test')
        validate_required_attributes(config, [:capability, :host_path, :name, :node_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_dynamic_host_volume_registration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_dynamic_host_volume_registration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_dynamic_host_volume_registration('test', required_attrs)

        expect(ref.id).to eq("${nomad_dynamic_host_volume_registration.test.id}")
        expect(ref.capacity_bytes).to eq("${nomad_dynamic_host_volume_registration.test.capacity_bytes}")
        expect(ref.capacity_max_bytes).to eq("${nomad_dynamic_host_volume_registration.test.capacity_max_bytes}")
        expect(ref.capacity_min_bytes).to eq("${nomad_dynamic_host_volume_registration.test.capacity_min_bytes}")
        expect(ref.constraint).to eq("${nomad_dynamic_host_volume_registration.test.constraint}")
        expect(ref.node_pool).to eq("${nomad_dynamic_host_volume_registration.test.node_pool}")
        expect(ref.plugin_id).to eq("${nomad_dynamic_host_volume_registration.test.plugin_id}")
        expect(ref.state).to eq("${nomad_dynamic_host_volume_registration.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'test')
        expect(config).not_to have_key('capacity_bytes')
        expect(config).not_to have_key('capacity_max_bytes')
        expect(config).not_to have_key('capacity_min_bytes')
        expect(config).not_to have_key('constraint')
        expect(config).not_to have_key('node_pool')
        expect(config).not_to have_key('plugin_id')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ capacity: 'test-value', namespace: 'test-value', parameters: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'full')
        expect(config).to have_key('capacity')
        expect(config).to have_key('namespace')
        expect(config).to have_key('parameters')
      end
    end

    context 'optional attributes' do
      it 'includes capacity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('opt', required_attrs.merge(capacity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'opt')
        expect(config).to have_key('capacity')
      end

      it 'omits capacity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'minimal')
        expect(config).not_to have_key('capacity')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes parameters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('opt', required_attrs.merge(parameters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'opt')
        expect(config).to have_key('parameters')
      end

      it 'omits parameters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'minimal')
        expect(config).not_to have_key('parameters')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume_registration', 'typed')
        expect(config['capability']).to be_a(Array)
        expect(config['host_path']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['node_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume_registration('first', required_attrs)
        synth.nomad_dynamic_host_volume_registration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_dynamic_host_volume_registration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_dynamic_host_volume_registration,
    method: :nomad_dynamic_host_volume_registration,
    required_attrs: { capability: [{ 'key1' => 'val1' }], host_path: 'test-value', name: 'test-value', node_id: 'test-value' },
    expected_outputs: [:id, :capacity_bytes, :capacity_max_bytes, :capacity_min_bytes, :constraint, :node_pool, :plugin_id, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
