# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_acl_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadAclToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { type: 'test-value' } }

  describe ':nomad_acl_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_acl_token', 'test')
        validate_required_attributes(config, [:type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_acl_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_token('test', required_attrs)

        expect(ref.id).to eq("${nomad_acl_token.test.id}")
        expect(ref.accessor_id).to eq("${nomad_acl_token.test.accessor_id}")
        expect(ref.create_time).to eq("${nomad_acl_token.test.create_time}")
        expect(ref.expiration_time).to eq("${nomad_acl_token.test.expiration_time}")
        expect(ref.secret_id).to eq("${nomad_acl_token.test.secret_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_token', 'test')
        expect(config).not_to have_key('accessor_id')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('expiration_time')
        expect(config).not_to have_key('secret_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expiration_ttl: 'test-value', global: true, name: 'test-value', policies: ['test-value'], role: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_token', 'full')
        expect(config).to have_key('expiration_ttl')
        expect(config).to have_key('global')
        expect(config).to have_key('name')
        expect(config).to have_key('policies')
        expect(config).to have_key('role')
      end
    end

    context 'optional attributes' do
      it 'includes expiration_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('opt', required_attrs.merge(expiration_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'opt')
        expect(config).to have_key('expiration_ttl')
      end

      it 'omits expiration_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'minimal')
        expect(config).not_to have_key('expiration_ttl')
      end
      it 'includes global when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('opt', required_attrs.merge(global: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'opt')
        expect(config).to have_key('global')
      end

      it 'omits global when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'minimal')
        expect(config).not_to have_key('global')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('opt', required_attrs.merge(policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'opt')
        expect(config).to have_key('policies')
      end

      it 'omits policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'minimal')
        expect(config).not_to have_key('policies')
      end
      it 'includes role when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('opt', required_attrs.merge(role: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'opt')
        expect(config).to have_key('role')
      end

      it 'omits role when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_token', 'minimal')
        expect(config).not_to have_key('role')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:secret_id]
        expect(sensitive_fields).to include(:secret_id)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts global=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(global: val)
          synth.nomad_acl_token("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_acl_token', "bool_#{val}")
          expect(config['global']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_token', 'typed')
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_token('first', required_attrs)
        synth.nomad_acl_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_acl_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_acl_token,
    method: :nomad_acl_token,
    required_attrs: { type: 'test-value' },
    expected_outputs: [:id, :accessor_id, :create_time, :expiration_time, :secret_id],
    sensitive_fields: [:secret_id],
    immutable_fields: [],
    boolean_fields: [:global]
end
