# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_scheduler_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadSchedulerConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':nomad_scheduler_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_scheduler_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_scheduler_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_scheduler_config('test', required_attrs)

        expect(ref.id).to eq("${nomad_scheduler_config.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ memory_oversubscription_enabled: true, preemption_config: { 'key1' => 'val1' }, scheduler_algorithm: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_scheduler_config', 'full')
        expect(config).to have_key('memory_oversubscription_enabled')
        expect(config).to have_key('preemption_config')
        expect(config).to have_key('scheduler_algorithm')
      end
    end

    context 'optional attributes' do
      it 'includes memory_oversubscription_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('opt', required_attrs.merge(memory_oversubscription_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'opt')
        expect(config).to have_key('memory_oversubscription_enabled')
      end

      it 'omits memory_oversubscription_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'minimal')
        expect(config).not_to have_key('memory_oversubscription_enabled')
      end
      it 'includes preemption_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('opt', required_attrs.merge(preemption_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'opt')
        expect(config).to have_key('preemption_config')
      end

      it 'omits preemption_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'minimal')
        expect(config).not_to have_key('preemption_config')
      end
      it 'includes scheduler_algorithm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('opt', required_attrs.merge(scheduler_algorithm: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'opt')
        expect(config).to have_key('scheduler_algorithm')
      end

      it 'omits scheduler_algorithm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_scheduler_config', 'minimal')
        expect(config).not_to have_key('scheduler_algorithm')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts memory_oversubscription_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(memory_oversubscription_enabled: val)
          synth.nomad_scheduler_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_scheduler_config', "bool_#{val}")
          expect(config['memory_oversubscription_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_scheduler_config', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_scheduler_config('first', required_attrs)
        synth.nomad_scheduler_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_scheduler_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_scheduler_config,
    method: :nomad_scheduler_config,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:memory_oversubscription_enabled]
end
