# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_acl_binding_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadAclBindingRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { auth_method: 'test-value', bind_type: 'test-value' } }

  describe ':nomad_acl_binding_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'test')
        validate_required_attributes(config, [:auth_method, :bind_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_binding_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_acl_binding_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_binding_rule('test', required_attrs)

        expect(ref.id).to eq("${nomad_acl_binding_rule.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ bind_name: 'test-value', description: 'test-value', selector: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'full')
        expect(config).to have_key('bind_name')
        expect(config).to have_key('description')
        expect(config).to have_key('selector')
      end
    end

    context 'optional attributes' do
      it 'includes bind_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('opt', required_attrs.merge(bind_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'opt')
        expect(config).to have_key('bind_name')
      end

      it 'omits bind_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'minimal')
        expect(config).not_to have_key('bind_name')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes selector when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('opt', required_attrs.merge(selector: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'opt')
        expect(config).to have_key('selector')
      end

      it 'omits selector when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'minimal')
        expect(config).not_to have_key('selector')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_binding_rule', 'typed')
        expect(config['auth_method']).to be_a(String)
        expect(config['bind_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_binding_rule('first', required_attrs)
        synth.nomad_acl_binding_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_acl_binding_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_acl_binding_rule,
    method: :nomad_acl_binding_rule,
    required_attrs: { auth_method: 'test-value', bind_type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
