# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_namespace resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadNamespace do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':nomad_namespace' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_namespace', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_namespace('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_namespace)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_namespace('test', required_attrs)

        expect(ref.id).to eq("${nomad_namespace.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ capabilities: [{ 'key1' => 'val1' }], description: 'test-value', meta: { 'key1' => 'val1' }, node_pool_config: [{ 'key1' => 'val1' }], quota: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_namespace', 'full')
        expect(config).to have_key('capabilities')
        expect(config).to have_key('description')
        expect(config).to have_key('meta')
        expect(config).to have_key('node_pool_config')
        expect(config).to have_key('quota')
      end
    end

    context 'optional attributes' do
      it 'includes capabilities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('opt', required_attrs.merge(capabilities: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'opt')
        expect(config).to have_key('capabilities')
      end

      it 'omits capabilities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'minimal')
        expect(config).not_to have_key('capabilities')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes node_pool_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('opt', required_attrs.merge(node_pool_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'opt')
        expect(config).to have_key('node_pool_config')
      end

      it 'omits node_pool_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'minimal')
        expect(config).not_to have_key('node_pool_config')
      end
      it 'includes quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('opt', required_attrs.merge(quota: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'opt')
        expect(config).to have_key('quota')
      end

      it 'omits quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_namespace', 'minimal')
        expect(config).not_to have_key('quota')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_namespace', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_namespace('first', required_attrs)
        synth.nomad_namespace('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_namespace')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_namespace,
    method: :nomad_namespace,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
