# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { jobspec: 'test-value' } }

  describe ':nomad_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_job', 'test')
        validate_required_attributes(config, [:jobspec])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_job('test', required_attrs)

        expect(ref.id).to eq("${nomad_job.test.id}")
        expect(ref.allocation_ids).to eq("${nomad_job.test.allocation_ids}")
        expect(ref.datacenters).to eq("${nomad_job.test.datacenters}")
        expect(ref.deployment_id).to eq("${nomad_job.test.deployment_id}")
        expect(ref.deployment_status).to eq("${nomad_job.test.deployment_status}")
        expect(ref.modify_index).to eq("${nomad_job.test.modify_index}")
        expect(ref.name).to eq("${nomad_job.test.name}")
        expect(ref.namespace).to eq("${nomad_job.test.namespace}")
        expect(ref.region).to eq("${nomad_job.test.region}")
        expect(ref.status).to eq("${nomad_job.test.status}")
        expect(ref.task_groups).to eq("${nomad_job.test.task_groups}")
        expect(ref.type).to eq("${nomad_job.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_job', 'test')
        expect(config).not_to have_key('allocation_ids')
        expect(config).not_to have_key('datacenters')
        expect(config).not_to have_key('deployment_id')
        expect(config).not_to have_key('deployment_status')
        expect(config).not_to have_key('modify_index')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('namespace')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('task_groups')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ deregister_on_destroy: true, deregister_on_id_change: true, detach: true, hcl2: [{ 'key1' => 'val1' }], json: true, policy_override: true, purge_on_destroy: true, read_allocation_ids: true, rerun_if_dead: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_job', 'full')
        expect(config).to have_key('deregister_on_destroy')
        expect(config).to have_key('deregister_on_id_change')
        expect(config).to have_key('detach')
        expect(config).to have_key('hcl2')
        expect(config).to have_key('json')
        expect(config).to have_key('policy_override')
        expect(config).to have_key('purge_on_destroy')
        expect(config).to have_key('read_allocation_ids')
        expect(config).to have_key('rerun_if_dead')
      end
    end

    context 'optional attributes' do
      it 'includes deregister_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(deregister_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('deregister_on_destroy')
      end

      it 'omits deregister_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('deregister_on_destroy')
      end
      it 'includes deregister_on_id_change when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(deregister_on_id_change: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('deregister_on_id_change')
      end

      it 'omits deregister_on_id_change when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('deregister_on_id_change')
      end
      it 'includes detach when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(detach: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('detach')
      end

      it 'omits detach when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('detach')
      end
      it 'includes hcl2 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(hcl2: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('hcl2')
      end

      it 'omits hcl2 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('hcl2')
      end
      it 'includes json when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(json: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('json')
      end

      it 'omits json when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('json')
      end
      it 'includes policy_override when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(policy_override: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('policy_override')
      end

      it 'omits policy_override when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('policy_override')
      end
      it 'includes purge_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(purge_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('purge_on_destroy')
      end

      it 'omits purge_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('purge_on_destroy')
      end
      it 'includes read_allocation_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(read_allocation_ids: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('read_allocation_ids')
      end

      it 'omits read_allocation_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('read_allocation_ids')
      end
      it 'includes rerun_if_dead when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('opt', required_attrs.merge(rerun_if_dead: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'opt')
        expect(config).to have_key('rerun_if_dead')
      end

      it 'omits rerun_if_dead when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_job', 'minimal')
        expect(config).not_to have_key('rerun_if_dead')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts deregister_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deregister_on_destroy: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['deregister_on_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts deregister_on_id_change=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deregister_on_id_change: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['deregister_on_id_change']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts detach=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(detach: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['detach']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts json=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(json: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['json']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts policy_override=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(policy_override: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['policy_override']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts purge_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(purge_on_destroy: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['purge_on_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts read_allocation_ids=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(read_allocation_ids: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['read_allocation_ids']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts rerun_if_dead=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(rerun_if_dead: val)
          synth.nomad_job("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_job', "bool_#{val}")
          expect(config['rerun_if_dead']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_job', 'typed')
        expect(config['jobspec']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_job('first', required_attrs)
        synth.nomad_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_job,
    method: :nomad_job,
    required_attrs: { jobspec: 'test-value' },
    expected_outputs: [:id, :allocation_ids, :datacenters, :deployment_id, :deployment_status, :modify_index, :name, :namespace, :region, :status, :task_groups, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:deregister_on_destroy, :deregister_on_id_change, :detach, :json, :policy_override, :purge_on_destroy, :read_allocation_ids, :rerun_if_dead]
end
