# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_node_pool resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadNodePool do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':nomad_node_pool' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_node_pool', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_node_pool('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_node_pool)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_node_pool('test', required_attrs)

        expect(ref.id).to eq("${nomad_node_pool.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', meta: { 'key1' => 'val1' }, scheduler_config: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_node_pool', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('meta')
        expect(config).to have_key('scheduler_config')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes scheduler_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('opt', required_attrs.merge(scheduler_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'opt')
        expect(config).to have_key('scheduler_config')
      end

      it 'omits scheduler_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_node_pool', 'minimal')
        expect(config).not_to have_key('scheduler_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_node_pool', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_node_pool('first', required_attrs)
        synth.nomad_node_pool('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_node_pool')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_node_pool,
    method: :nomad_node_pool,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
