# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_acl_auth_method resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadAclAuthMethod do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { config: [{ 'key1' => 'val1' }], max_token_ttl: 'test-value', name: 'test-value', token_locality: 'test-value', type: 'test-value' } }

  describe ':nomad_acl_auth_method' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'test')
        validate_required_attributes(config, [:config, :max_token_ttl, :name, :token_locality, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_auth_method('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_acl_auth_method)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_acl_auth_method('test', required_attrs)

        expect(ref.id).to eq("${nomad_acl_auth_method.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default: true, token_name_format: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'full')
        expect(config).to have_key('default')
        expect(config).to have_key('token_name_format')
      end
    end

    context 'optional attributes' do
      it 'includes default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('opt', required_attrs.merge(default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'opt')
        expect(config).to have_key('default')
      end

      it 'omits default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'minimal')
        expect(config).not_to have_key('default')
      end
      it 'includes token_name_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('opt', required_attrs.merge(token_name_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'opt')
        expect(config).to have_key('token_name_format')
      end

      it 'omits token_name_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'minimal')
        expect(config).not_to have_key('token_name_format')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(default: val)
          synth.nomad_acl_auth_method("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'nomad_acl_auth_method', "bool_#{val}")
          expect(config['default']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_acl_auth_method', 'typed')
        expect(config['config']).to be_a(Array)
        expect(config['max_token_ttl']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['token_locality']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_acl_auth_method('first', required_attrs)
        synth.nomad_acl_auth_method('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_acl_auth_method')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_acl_auth_method,
    method: :nomad_acl_auth_method,
    required_attrs: { config: [{ 'key1' => 'val1' }], max_token_ttl: 'test-value', name: 'test-value', token_locality: 'test-value', type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:default]
end
