# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_external_volume resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadExternalVolume do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { capability: [{ 'key1' => 'val1' }], name: 'test-value', plugin_id: 'test-value', volume_id: 'test-value' } }

  describe ':nomad_external_volume' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_external_volume', 'test')
        validate_required_attributes(config, [:capability, :name, :plugin_id, :volume_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_external_volume('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_external_volume)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_external_volume('test', required_attrs)

        expect(ref.id).to eq("${nomad_external_volume.test.id}")
        expect(ref.controller_required).to eq("${nomad_external_volume.test.controller_required}")
        expect(ref.controllers_expected).to eq("${nomad_external_volume.test.controllers_expected}")
        expect(ref.controllers_healthy).to eq("${nomad_external_volume.test.controllers_healthy}")
        expect(ref.nodes_expected).to eq("${nomad_external_volume.test.nodes_expected}")
        expect(ref.nodes_healthy).to eq("${nomad_external_volume.test.nodes_healthy}")
        expect(ref.plugin_provider).to eq("${nomad_external_volume.test.plugin_provider}")
        expect(ref.plugin_provider_version).to eq("${nomad_external_volume.test.plugin_provider_version}")
        expect(ref.schedulable).to eq("${nomad_external_volume.test.schedulable}")
        expect(ref.topologies).to eq("${nomad_external_volume.test.topologies}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_external_volume', 'test')
        expect(config).not_to have_key('controller_required')
        expect(config).not_to have_key('controllers_expected')
        expect(config).not_to have_key('controllers_healthy')
        expect(config).not_to have_key('nodes_expected')
        expect(config).not_to have_key('nodes_healthy')
        expect(config).not_to have_key('plugin_provider')
        expect(config).not_to have_key('plugin_provider_version')
        expect(config).not_to have_key('schedulable')
        expect(config).not_to have_key('topologies')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ capacity_max: 'test-value', capacity_min: 'test-value', clone_id: 'test-value', mount_options: [{ 'key1' => 'val1' }], namespace: 'test-value', parameters: { 'key1' => 'val1' }, secrets: { 'key1' => 'val1' }, snapshot_id: 'test-value', topology_request: [{ 'key1' => 'val1' }], type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_external_volume', 'full')
        expect(config).to have_key('capacity_max')
        expect(config).to have_key('capacity_min')
        expect(config).to have_key('clone_id')
        expect(config).to have_key('mount_options')
        expect(config).to have_key('namespace')
        expect(config).to have_key('parameters')
        expect(config).to have_key('secrets')
        expect(config).to have_key('snapshot_id')
        expect(config).to have_key('topology_request')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes capacity_max when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(capacity_max: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('capacity_max')
      end

      it 'omits capacity_max when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('capacity_max')
      end
      it 'includes capacity_min when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(capacity_min: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('capacity_min')
      end

      it 'omits capacity_min when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('capacity_min')
      end
      it 'includes clone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(clone_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('clone_id')
      end

      it 'omits clone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('clone_id')
      end
      it 'includes mount_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(mount_options: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('mount_options')
      end

      it 'omits mount_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('mount_options')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes parameters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(parameters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('parameters')
      end

      it 'omits parameters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('parameters')
      end
      it 'includes secrets when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(secrets: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('secrets')
      end

      it 'omits secrets when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('secrets')
      end
      it 'includes snapshot_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(snapshot_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('snapshot_id')
      end

      it 'omits snapshot_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('snapshot_id')
      end
      it 'includes topology_request when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(topology_request: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('topology_request')
      end

      it 'omits topology_request when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('topology_request')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_external_volume', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:secrets]
        expect(sensitive_fields).to include(:secrets)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_external_volume', 'typed')
        expect(config['capability']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['plugin_id']).to be_a(String)
        expect(config['volume_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_external_volume('first', required_attrs)
        synth.nomad_external_volume('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_external_volume')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_external_volume,
    method: :nomad_external_volume,
    required_attrs: { capability: [{ 'key1' => 'val1' }], name: 'test-value', plugin_id: 'test-value', volume_id: 'test-value' },
    expected_outputs: [:id, :controller_required, :controllers_expected, :controllers_healthy, :nodes_expected, :nodes_healthy, :plugin_provider, :plugin_provider_version, :schedulable, :topologies],
    sensitive_fields: [:secrets],
    immutable_fields: [],
    boolean_fields: []
end
