# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a nomad_dynamic_host_volume resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NomadDynamicHostVolume do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { capability: [{ 'key1' => 'val1' }], name: 'test-value', plugin_id: 'test-value' } }

  describe ':nomad_dynamic_host_volume' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'test')
        validate_required_attributes(config, [:capability, :name, :plugin_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_dynamic_host_volume('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:nomad_dynamic_host_volume)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.nomad_dynamic_host_volume('test', required_attrs)

        expect(ref.id).to eq("${nomad_dynamic_host_volume.test.id}")
        expect(ref.capacity).to eq("${nomad_dynamic_host_volume.test.capacity}")
        expect(ref.capacity_bytes).to eq("${nomad_dynamic_host_volume.test.capacity_bytes}")
        expect(ref.capacity_max_bytes).to eq("${nomad_dynamic_host_volume.test.capacity_max_bytes}")
        expect(ref.capacity_min_bytes).to eq("${nomad_dynamic_host_volume.test.capacity_min_bytes}")
        expect(ref.host_path).to eq("${nomad_dynamic_host_volume.test.host_path}")
        expect(ref.node_id).to eq("${nomad_dynamic_host_volume.test.node_id}")
        expect(ref.node_pool).to eq("${nomad_dynamic_host_volume.test.node_pool}")
        expect(ref.state).to eq("${nomad_dynamic_host_volume.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'test')
        expect(config).not_to have_key('capacity')
        expect(config).not_to have_key('capacity_bytes')
        expect(config).not_to have_key('capacity_max_bytes')
        expect(config).not_to have_key('capacity_min_bytes')
        expect(config).not_to have_key('host_path')
        expect(config).not_to have_key('node_id')
        expect(config).not_to have_key('node_pool')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ capacity_max: 'test-value', capacity_min: 'test-value', constraint: [{ 'key1' => 'val1' }], namespace: 'test-value', parameters: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'full')
        expect(config).to have_key('capacity_max')
        expect(config).to have_key('capacity_min')
        expect(config).to have_key('constraint')
        expect(config).to have_key('namespace')
        expect(config).to have_key('parameters')
      end
    end

    context 'optional attributes' do
      it 'includes capacity_max when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('opt', required_attrs.merge(capacity_max: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'opt')
        expect(config).to have_key('capacity_max')
      end

      it 'omits capacity_max when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'minimal')
        expect(config).not_to have_key('capacity_max')
      end
      it 'includes capacity_min when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('opt', required_attrs.merge(capacity_min: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'opt')
        expect(config).to have_key('capacity_min')
      end

      it 'omits capacity_min when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'minimal')
        expect(config).not_to have_key('capacity_min')
      end
      it 'includes constraint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('opt', required_attrs.merge(constraint: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'opt')
        expect(config).to have_key('constraint')
      end

      it 'omits constraint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'minimal')
        expect(config).not_to have_key('constraint')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes parameters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('opt', required_attrs.merge(parameters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'opt')
        expect(config).to have_key('parameters')
      end

      it 'omits parameters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'minimal')
        expect(config).not_to have_key('parameters')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'nomad_dynamic_host_volume', 'typed')
        expect(config['capability']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['plugin_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.nomad_dynamic_host_volume('first', required_attrs)
        synth.nomad_dynamic_host_volume('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'nomad_dynamic_host_volume')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :nomad_dynamic_host_volume,
    method: :nomad_dynamic_host_volume,
    required_attrs: { capability: [{ 'key1' => 'val1' }], name: 'test-value', plugin_id: 'test-value' },
    expected_outputs: [:id, :capacity, :capacity_bytes, :capacity_max_bytes, :capacity_min_bytes, :host_path, :node_id, :node_pool, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
