# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/nomad_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NomadJob
    include Pangea::Resources::ResourceBuilder

    define_resource :nomad_job,
      attributes_class: Nomad::Types::JobAttributes,
      outputs: { id: :id },
      map: [:jobspec],
      map_present: [:hcl2],
      map_bool: [:deregister_on_destroy, :deregister_on_id_change, :detach, :json, :policy_override, :purge_on_destroy, :read_allocation_ids, :rerun_if_dead]
  end
  module Nomad
    include NomadJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Nomad)
