# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Nomad::Types
  include Dry.Types()

  class JobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Nomad::Types

    attribute :jobspec, T::String
    attribute? :deregister_on_destroy, T::Bool.optional
    attribute? :deregister_on_id_change, T::Bool.optional
    attribute? :detach, T::Bool.optional
    attribute? :hcl2, T::Array.of(T::Hash).optional
    attribute? :json, T::Bool.optional
    attribute? :policy_override, T::Bool.optional
    attribute? :purge_on_destroy, T::Bool.optional
    attribute? :read_allocation_ids, T::Bool.optional
    attribute? :rerun_if_dead, T::Bool.optional
  end
end
